---
title: "manta_rays_data_reproduce"
format: html
---

```{r, echo=TRUE, message=FALSE, warning=FALSE, eval=FALSE}
source(here::here("data-raw/data_reproduce_utiles.R"))
```

## Define Global Parameters

```{r, echo=TRUE, message=FALSE, warning=FALSE, eval=FALSE}
organism_name <- "manta_rays"
organism_title <- "Manta Rays"
taxa <- "Mobula alfredi"
start <- 2014
end <- 2024
email <- "your_email@gmail.com"
```

## Step 1: Download and Prepare Data

```{r, echo=TRUE, message=FALSE, warning=FALSE, eval=FALSE}
organism <- obs_data(taxa, start, end, your_email=email) |> 
  polished_data() |> 
  filter(sci_name == "Mobula alfredi")
```

```{r, echo=TRUE, message=FALSE, warning=FALSE, eval=FALSE}

organism <- organism |> filter(between(obs_lon, 115, 160), between(obs_lat, -45, -10))
```

## Step 2: Save Cleaned Dataset

```{r, echo=TRUE, message=FALSE, warning=FALSE, eval=FALSE}
mysave(organism_name, organism)
```

## Step 3: Attach Nearest Weather Station

```{r, echo=TRUE, message=FALSE, warning=FALSE, eval=FALSE}
attach_nearest_station(organism_name)
```

## Step 4: Load and Preview Final Dataset

```{r, echo=TRUE, message=FALSE, warning=FALSE, eval=FALSE}
load("../data/manta_rays.rda")
glimpse(manta_rays)
```
