---
title: "orchids_data_reproduce"
format: html
---

```{r, echo=TRUE, message=FALSE, warning=FALSE, eval=FALSE}
source(here::here("data-raw/data_reproduce_utiles.R"))
```

## Define Global Parameters

```{r, echo=TRUE, message=FALSE, warning=FALSE, eval=FALSE}
organism_name <- "orchids"
organism_title <- "Orchids"
taxa <- "Orchidaceae"
start <- 2014
end <- 2024
email <- "your_email@email.com"
```

## Step 1: Download and Prepare Data

```{r, echo=TRUE, message=FALSE, warning=FALSE, eval=FALSE}
organism <- obs_data(taxa, start, end, your_email=email) |> polished_data()
```

```{r echo=TRUE, message=FALSE, warning=FALSE, eval=FALSE}
# Choosing a subset of species
orchids_subset <- read_csv(here::here("data-raw/orchids_subset.csv"))
organism <- organism %>%
  mutate(
    genus   = word(sci_name, 1),
    epithet = word(sci_name, 2),
    # species-level if it has two words and the 2nd isn't a vague token
    is_species = !is.na(epithet) &
      !str_detect(epithet, "^(sp|spp|cf|aff|x|×)\\.?$"),
    binomial = if_else(is_species, paste(genus, epithet), NA_character_)
  )

organism <- organism |>
  filter(is_species==TRUE, 
         sci_name %in% orchids_subset$scientificName,
         obs_state == "Western Australia") |> 
  select(1:13)
```

## Step 2: Save Cleaned Dataset

```{r, echo=TRUE, message=FALSE, warning=FALSE, eval=FALSE}
mysave(organism_name, organism)
```

## Step 3: Attach Nearest Weather Station

```{r, echo=TRUE, message=FALSE, warning=FALSE, eval=FALSE}
attach_nearest_station(organism_name)
```

## Step 4: Load and Preview Final Dataset

```{r, echo=TRUE, message=FALSE, warning=FALSE, eval=FALSE}
load(here::here("data/orchids.rda"))
glimpse(orchids)
```
