---
title: "weather data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{weather_data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
source("vignette-utils.R")
```

```{r, echo=FALSE, eval=TRUE}
organism_names <- c("orchids", "gouldian_finch", "manta_rays", "glowworms")

# Load the station metadata once
load("../data/weather_stations.rda")

# Initialize an empty list to store results
all_top_stations <- list()

for (org in organism_names) {
  # Load organism weather-station dataset
  load(paste0("../data/", org, "_ws.rda"))
  org_data <- get(paste0(org, "_ws"))
  
  # Count and get top 3 stations
  top_stations <- org_data %>%
    count(weather_station_id, sort = TRUE) %>%
    slice_max(n, n = 3) %>%
    left_join(weather_stations, by = c("weather_station_id")) %>%
    mutate(organism = org) %>%
    select(organism, weather_station_id)
  
  # Store in the list
  all_top_stations[[org]] <- top_stations
}

# Combine all into a single data frame
top_stations <- bind_rows(all_top_stations)

# Optional: save
save(top_stations, file = "../data/top_stations.rda")

```

Top 3 Stations for Each Organism: 

```{r, echo=FALSE, eval=TRUE}
load("../data/weather_stations.rda")
load("../data/top_stations.rda")

df <- left_join(top_stations, weather_stations, by = "weather_station_id")
df
```


```{r, echo=FALSE, fig.height=5, fig.width=7}
aus_map <- ne_states(country = "Australia", returnclass = "sf")
ggplot() +
  geom_sf(data = aus_map, fill = "gray95", color = "gray50") +
  geom_point(data = df, aes(x = stn_lon, y = stn_lat, color = organism), shape = 2, alpha = 5, size = 3) +
  coord_sf(xlim = c(110, 155), ylim = c(-45, -10)) +
  theme_minimal()
```



```{r echo=FALSE, eval=FALSE}
# Get weather data for top 3 stations (optional)

weather_data_list <- lapply(top_stations$weather_station_id, function(stn) {
  get_GSOD(years = 2014:2024, station = stn)
})

# Combine and save
top_weather <- dplyr::bind_rows(weather_data_list)

# Combine and save
top_weather <- dplyr::bind_rows(weather_data_list) |> 
  transmute(
      weather_station_id = STNID,
      stn_lat = LATITUDE,
      stn_lon = LONGITUDE,
      date = YEARMODA,
      year = YEAR,
      month = MONTH,
      day = DAY,
      weekday = lubridate::wday(date, label = TRUE, abbr = FALSE,                                 week_start = getOption("lubridate.week.start", 1)),
      dayofyear = YDAY,
      temp = TEMP,
      min = MIN,
      max = MAX,
      dewp = DEWP,
      rh = RH,
      prcp = PRCP,
      rainy = ifelse(PRCP > 5, 1, 0),
      wind_speed = WDSP,
      max_speed = MXSPD
    )


# Dynamically assign it to the global environment under a specific name
obj_name <- paste0("weather_data")
file_path <- file.path("../data", paste0(obj_name, ".rda"))
assign(obj_name, top_weather)

save(list = obj_name, file = file_path)

```

The weather data for all top station and one decade (2014-2024) saved in `data/` with name `weather_data.rda`.

```{r, echo=FALSE}

load("../data/weather_data.rda")
weather_data |> glimpse()
```
