---
title: "weather_data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{weather_data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

#### Download Weather Data for Top 3 Stations

```{r echo=FALSE, message=FALSE, warning=FALSE}
# load required packages
library(GSODR)
library(tidyverse)
library(geosphere)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
```

##### Top 3 Station for **Orchids**
```{r echo=FALSE}
organism <- "orchids"
# Load required data
load(paste0("../data/", organism, "_ws.rda"))
load("../data/weather_stations.rda")

# Identify top 3 stations
station_counts <- get(paste0(organism, "_ws")) %>%
  count(weather_station_id, sort = TRUE) %>%
  left_join(weather_stations, by = c("weather_station_id" = "stnid")) %>%
  distinct()

head(station_counts, n = 3)

```

```{r, echo=FALSE, fig.height=6, fig.width=8}
aus_map <- ne_states(country = "Australia", returnclass = "sf")
ggplot() +
  geom_sf(data = aus_map, fill = "gray95", color = "gray50") +
 geom_point(data = orchids_ws, aes(x = obs_lon, y = obs_lat, color = obs_state), alpha = 0.6, size = 1.5) +
  geom_point(data = station_counts[1:3,], aes(x = stn_lon, y = stn_lat), shape = 2, alpha = 1, size = 2) +
  coord_sf(xlim = c(110, 155), ylim = c(-45, -10)) +
  theme_minimal()
```

```{r echo=FALSE, eval=FALSE}
# Get weather data for top 3 stations (optional)
top_stations <- station_counts |> slice_max(n, n = 3)

weather_data_list <- lapply(top_stations$weather_station_id, function(stn) {
  get_GSOD(years = 2014:2024, station = stn)
})

# Combine and save
top_weather <- dplyr::bind_rows(weather_data_list)

# Combine and save
top_weather <- dplyr::bind_rows(weather_data_list) |> 
  transmute(
      weather_station_id = STNID,
      stn_lat = LATITUDE,
      stn_lon = LONGITUDE,
      datetime = YEARMODA,
      year = YEAR,
      month = MONTH,
      day = DAY,
      dayofyear = YDAY,
      temp = TEMP,
      min = MIN,
      max = MAX,
      dewp = DEWP,
      rh = RH,
      wind_speed = WDSP,
      max_speed = MXSPD
    )


# Dynamically assign it to the global environment under a specific name
obj_name <- paste0(organism, "_top_weather")
file_path <- file.path("../data", paste0(obj_name, ".rda"))
assign(obj_name, top_weather)

save(list = obj_name, file = file_path)

```


##### Top 3 Station for **Gouldian finch**
```{r echo=FALSE}
organism <- "gouldian_finch"
# Load required data
load(paste0("../data/", organism, "_ws.rda"))
load("../data/weather_stations.rda")

# Identify top 3 stations
station_counts <- get(paste0(organism, "_ws")) %>%
  count(weather_station_id, sort = TRUE) %>%
  left_join(weather_stations, by = c("weather_station_id" = "stnid")) %>%
  distinct()

head(station_counts, n = 3)

```

```{r, echo=FALSE, fig.height=6, fig.width=8}
aus_map <- ne_states(country = "Australia", returnclass = "sf")
ggplot() +
  geom_sf(data = aus_map, fill = "gray95", color = "gray50") +
 geom_point(data = gouldian_finch_ws, aes(x = obs_lon, y = obs_lat, color = obs_state), alpha = 0.6, size = 1.5) +
  geom_point(data = station_counts[1:3,], aes(x = stn_lon, y = stn_lat), shape = 2, alpha = 1, size = 2) +
  coord_sf(xlim = c(110, 155), ylim = c(-45, -10)) +
  theme_minimal()
```

```{r echo=FALSE, eval=FALSE}
# Get weather data for top 3 stations (optional)
top_stations <- station_counts |> slice_max(n, n = 3)

weather_data_list <- lapply(top_stations$weather_station_id, function(stn) {
  get_GSOD(years = 2014:2024, station = stn)
})

# Combine and save
top_weather <- dplyr::bind_rows(weather_data_list)

# Combine and save
top_weather <- dplyr::bind_rows(weather_data_list) |> 
  transmute(
      weather_station_id = STNID,
      stn_lat = LATITUDE,
      stn_lon = LONGITUDE,
      datetime = YEARMODA,
      year = YEAR,
      month = MONTH,
      day = DAY,
      dayofyear = YDAY,
      temp = TEMP,
      min = MIN,
      max = MAX,
      dewp = DEWP,
      rh = RH,
      wind_speed = WDSP,
      max_speed = MXSPD
    )


# Dynamically assign it to the global environment under a specific name
obj_name <- paste0(organism, "_top_weather")
file_path <- file.path("../data", paste0(obj_name, ".rda"))
assign(obj_name, top_weather)

save(list = obj_name, file = file_path)

```


##### Top 3 Station for **Glowworms**
```{r echo=FALSE}
organism <- "glowworms"
# Load required data
load(paste0("../data/", organism, "_ws.rda"))
load("../data/weather_stations.rda")

# Identify top 3 stations
station_counts <- get(paste0(organism, "_ws")) %>%
  count(weather_station_id, sort = TRUE) %>%
  left_join(weather_stations, by = c("weather_station_id" = "stnid")) %>%
  distinct()

head(station_counts, n = 3)

```

```{r, echo=FALSE, fig.height=6, fig.width=8}
aus_map <- ne_states(country = "Australia", returnclass = "sf")
ggplot() +
  geom_sf(data = aus_map, fill = "gray95", color = "gray50") +
 geom_point(data = glowworms_ws, aes(x = obs_lon, y = obs_lat, color = obs_state), alpha = 0.6, size = 1.5) +
  geom_point(data = station_counts[1:3,], aes(x = stn_lon, y = stn_lat), shape = 2, alpha = 1, size = 2) +
  coord_sf(xlim = c(110, 155), ylim = c(-45, -10)) +
  theme_minimal()
```



```{r echo=FALSE, eval=FALSE}
# Get weather data for top 3 stations (optional)
top_stations <- station_counts |> slice_max(n, n = 3)

weather_data_list <- lapply(top_stations$weather_station_id, function(stn) {
  get_GSOD(years = 2014:2024, station = stn)
})

# Combine and save
top_weather <- dplyr::bind_rows(weather_data_list)

# Combine and save
top_weather <- dplyr::bind_rows(weather_data_list) |> 
  transmute(
      weather_station_id = STNID,
      stn_lat = LATITUDE,
      stn_lon = LONGITUDE,
      datetime = YEARMODA,
      year = YEAR,
      month = MONTH,
      day = DAY,
      dayofyear = YDAY,
      temp = TEMP,
      min = MIN,
      max = MAX,
      dewp = DEWP,
      rh = RH,
      wind_speed = WDSP,
      max_speed = MXSPD
    )


# Dynamically assign it to the global environment under a specific name
obj_name <- paste0(organism, "_top_weather")
file_path <- file.path("../data", paste0(obj_name, ".rda"))
assign(obj_name, top_weather)

save(list = obj_name, file = file_path)
```



##### Top 3 Station for **Manta Rays**
```{r echo=FALSE}
organism <- "manta_rays"
# Load required data
load(paste0("../data/", organism, "_ws.rda"))
load("../data/weather_stations.rda")

# Identify top 3 stations
station_counts <- get(paste0(organism, "_ws")) %>%
  count(weather_station_id, sort = TRUE) %>%
  left_join(weather_stations, by = c("weather_station_id" = "stnid")) %>%
  distinct()

head(station_counts, n = 3)

```


```{r, echo=FALSE, fig.height=6, fig.width=8}
aus_map <- ne_states(country = "Australia", returnclass = "sf")
ggplot() +
  geom_sf(data = aus_map, fill = "gray95", color = "gray50") +
 geom_point(data = manta_rays_ws, aes(x = obs_lon, y = obs_lat, color = obs_state), alpha = 0.6, size = 1.5) +
  geom_point(data = station_counts[1:3,], aes(x = stn_lon, y = stn_lat), shape = 2, alpha = 1, size = 2) +
  coord_sf(xlim = c(110, 155), ylim = c(-45, -10)) +
  theme_minimal()
```


```{r echo=FALSE, eval=FALSE}
# Get weather data for top 3 stations (optional)
top_stations <- station_counts |> slice_max(n, n = 3)

weather_data_list <- lapply(top_stations$weather_station_id, function(stn) {
  get_GSOD(years = 2014:2024, station = stn)
})

# Combine and save
top_weather <- dplyr::bind_rows(weather_data_list) |> 
  transmute(
      weather_station_id = STNID,
      stn_lat = LATITUDE,
      stn_lon = LONGITUDE,
      datetime = YEARMODA,
      year = YEAR,
      month = MONTH,
      day = DAY,
      dayofyear = YDAY,
      temp = TEMP,
      min = MIN,
      max = MAX,
      dewp = DEWP,
      rh = RH,
      wind_speed = WDSP,
      max_speed = MXSPD
    )


# Dynamically assign it to the global environment under a specific name
obj_name <- paste0(organism, "_top_weather")
file_path <- file.path("../data", paste0(obj_name, ".rda"))
assign(obj_name, top_weather)

save(list = obj_name, file = file_path)
```

